### ISSUE TITLE
upgrade footer and add footer pages

### ISSUE THREAD

**Issue by PettraV** [CodeCatz/TrackCat#93] opened 2015-01-17 15:03 UTC
@anuschka @fbbunny  and design team, give me two or three footer examples you like, color numbers, font-family, background color i have to use.

**Comment by anuschka** [comment] 2015-01-17 16:05
Punce meni je všeč footer tukaj (skrolaj na dno itak) http://littlebits.cc/projects?page=2&order_by=published_at in tukaj http://codeweek.eu/. Glede barv poglej z right click-inspect element. Mogoce je kaksne lazji nacin na MACu. Glede fontov in ikonic imaš že inštalirane v repositorju   Font Awesome http://fontawesome.io/icons/. Poglej pod http://fontawesome.io/examples/ kako ga uporabiš v kodi.

**Comment by anuschka** [comment] 2015-01-17 16:57
V tisti slikah za dizajn sem tudi malo opisala skicirala footer :-)

**Comment by PettraV** [comment] 2015-01-17 17:00
Kul, primerki so mi vsec, za nekaj linkov v footerju bom vzpostavila nove strani (privacy, webmaster...), usp ENG, thanks for the icons, I was looking for this kind of staff, now just let me know what kind of colors on font-family we have to follow, so all pages will be synchronized with the same look. Wooohooo, we are heavily adding flash to the bones :+1:

**Comment by PettraV** [comment] 2015-01-17 17:06
Ql, I saw, i will try to do something like codeweek and add map if it will not to big. Will do something till Wednesday and then we will finalize the idea together :)

**Comment by fbbunny** [comment] 2015-01-17 17:12
I agree with @anuschka - these footers are nice :) I plan on working on the design code tomorrow.

**Comment by goranche** [comment] 2015-01-18 18:28
good to see you went back to english :wink:

**Comment by ialja** [comment] 2015-02-02 13:22
This seems like a duplicate of #55 - closing this issue, as the other one seems better defined.

**Closed by ialja** 2015-02-02 13:22 UTC
